#include "../EASUI.h"

int SET_NEW_EASUI_SCREEN(EASUI_SCREEN* SCREEN, uint16_t MAX_ELEMENT_COUNT)
{

    // [SET BASE VALUES]
    {

        SCREEN->TYPE = E_EASUI_SCREEN;
        SCREEN->ADD_ELEMENT = CONTAINER_ADD_ELEMENT;
        SCREEN->LAST_ELEMENT_INDEX = CONTAINER_LAST_ELEMENT_INDEX;
        SCREEN->MAX_ELEMENT_COUNT = MAX_ELEMENT_COUNT;

    }


    // [ALLOCATE MEMORY FOR ELEMENT LIST]
    {

        SCREEN->CHILDREN_LIST = MEMORY_ARENA_ALLOC(sizeof(EASUI_ELEMENT*) * MAX_ELEMENT_COUNT + 1);

        if (SCREEN->CHILDREN_LIST == NULL)
        {
            return EASUI_ERROR;
        }


        SCREEN->CHILDREN_LIST[0] = NULL;

    }

    return EASUI_OK;

}


