 #include "../EASUI.h"

int SET_WINDOW_SCREEN(EASUI_WINDOW* WINDOW, EASUI_SCREEN* SCREEN);

int SET_NEW_EASUI_WINDOW(EASUI_WINDOW* WINDOW, uint16_t MAX_ELEMENT_COUNT, EASUIvec2 SIZE)
{
        // [SET BASE VALUES]
        {
                WINDOW->TYPE = E_EASUI_WINDOW;
                WINDOW->MAX_ELEMENT_COUNT = MAX_ELEMENT_COUNT;
                WINDOW->SIZE = SIZE;

                WINDOW->ADD_ELEMENT = CONTAINER_ADD_ELEMENT;
                WINDOW->LAST_ELEMENT_INDEX = CONTAINER_LAST_ELEMENT_INDEX;
                WINDOW->SET_SCREEN = SET_WINDOW_SCREEN;;
        }

        // [ALLOCATE MEMORY FOR ELEMENT LIST]
        {

            WINDOW->CHILDREN_LIST = MEMORY_ARENA_ALLOC(sizeof(EASUI_ELEMENT*) * MAX_ELEMENT_COUNT + 1);

            if (WINDOW->CHILDREN_LIST == NULL)
            {
                return EASUI_ERROR;
            }


            WINDOW->CHILDREN_LIST[0] = NULL;

        }

        return EASUI_OK;
}

int SET_WINDOW_SCREEN(EASUI_WINDOW* WINDOW, EASUI_SCREEN* SCREEN) 
{ 
    WINDOW->CURRENT_SCREEN = SCREEN;  
    if (!WINDOW->CURRENT_SCREEN) return EASUI_ERROR;

    return EASUI_OK;
}


